name: deploy to s3, cloudfront
# 이벤트정의(트리거)
on:
    push:
        branches:
            - main
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # uses: 재사용이 가능한 사전에 만들어진 작업절차
            - uses: actions/checkout@v2

            - name: setup nodejs
              uses: actions/setup-node@v2
              with:
                node-version: '22'

            # run은 개발자가 직접 작업을 정의
            - name: npm install
              working-directory: .
              run: npm install
            
            - name: npm build
              working-directory: .
              run: npm run build

            - name: setup aws cli
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{secrets.AWS_ACCESS_KEY}}
                aws-secret-access-key: ${{secrets.AWS_SECRET_KEY}}
                aws-region: "ap-north-east-2"
            
            - name: deploy to s3
              run: aws s3 cp ./dist s3://www.purewa.shop/ --recursive

            - name: invalidate cloudfront
              run: aws cloudfront create-invalidation --distribution-id E2FG8AACQY7195 --paths "/*"
          